version: 2
updates:
  - package-ecosystem: composer
    directory: /backend/api
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: pub
    directory: /apps/assisted_mobile
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /apps/caregiver_mobile
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /apps/wear_os
    schedule:
      interval: weekly
  - package-ecosystem: swift
    directory: /apps/watchos
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

