// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        _assertConfigured(android, 'android');
        return android;
      case TargetPlatform.iOS:
        _assertConfigured(ios, 'ios');
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static void _assertConfigured(FirebaseOptions options, String platform) {
    if (options.apiKey.isEmpty) {
      throw UnsupportedError(
        'Firebase $platform options are not configured. '
        'Pass the Firebase API key with --dart-define.',
      );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:153278137136:ios:3a86738a98bd421c9e3ef5',
    messagingSenderId: '153278137136',
    projectId: 'fall-guardian-e6d5b',
    storageBucket: 'fall-guardian-e6d5b.firebasestorage.app',
    iosBundleId: 'com.fallguardian.caregiverApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:153278137136:android:ad54523252c6c38f9e3ef5',
    messagingSenderId: '153278137136',
    projectId: 'fall-guardian-e6d5b',
    storageBucket: 'fall-guardian-e6d5b.firebasestorage.app',
  );
}
